// <auto-generated />
namespace Rock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddDataViewSearchResultsAndReportSearchResultPages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rollup_0609));
        
        string IMigrationMetadata.Id
        {
            get { return "202206121415348_AddDataViewSearchResultsAndReportSearchResultPages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
