//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { ContentLibraryFilterControl } from "@Obsidian/Enums/CMS/contentLibraryFilterControl";
import { ContentLibraryFilterSelection } from "@Obsidian/Enums/CMS/contentLibraryFilterSelection";
import { ContentLibraryAttributeFilterSettingsBag } from "@Obsidian/ViewModels/CMS/contentLibraryAttributeFilterSettingsBag";

/** Defines the settings used by the Content Library filters. */
export type ContentLibraryFilterSettingsBag = {
    /**
     * Gets or sets a value indicating if personalization segments should
     * be used when indexing and filtering content.
     */
    isPersonalizationSegmentsEnabled: boolean;

    /**
     * Gets or sets a value indicating if personalization request filters
     * should be used when filtering content.
     */
    isPersonalizationRequestFiltersEnabled: boolean;

    /** Gets or sets a value indicating whether full text search should be enabled. */
    fullTextSearchEnabled: boolean;

    /**
     * Gets or sets a value indicating whether searching content by year
     * should be enabled.
     */
    yearSearchEnabled: boolean;

    /**
     * Gets or sets the label to use for the filter that allows an
     * individual to search for content by a specific year.
     */
    yearSearchLabel?: string | null;

    /** Gets or sets the year search filter control. */
    yearSearchFilterControl: ContentLibraryFilterControl;

    /** Gets or sets the selection type to use for the Year filter. */
    yearSearchFilterSelection: ContentLibraryFilterSelection;

    /**
     * Gets or sets the attributes that are enabled for filtering
     * and indexing on the content library.
     */
    attributeFilters?: ContentLibraryAttributeFilterSettingsBag[] | null;
};
