//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { ContentLibraryFilterControl } from "@Obsidian/Enums/CMS/contentLibraryFilterControl";
import { ContentLibraryFilterSelection } from "@Obsidian/Enums/CMS/contentLibraryFilterSelection";
import { Guid } from "@Obsidian/Types";

/** The settings for a single attribute filter configured on a content library. */
export type ContentLibraryAttributeFilterSettingsBag = {
    /**
     * Gets or sets the attribute key to use when accessing values
     * for this filter.
     */
    attributeKey?: Guid | null;

    /** Gets or sets the label to use for the filter. */
    label?: string | null;

    /** Gets or sets the search filter control. */
    filterControl: ContentLibraryFilterControl;

    /** Gets or sets the selection type to use for the filter. */
    filterSelection: ContentLibraryFilterSelection;
};
